pipeline {
    agent any
    
    stages {
        stage('Clonar Repositorio') {
            steps {
                git 'https://github.com/JuanCamiloBlandon/Product-Prowess.git'
            }
        }
        
        stage('Instalar dependencias') {
            steps {
                sh 'npm install'
            }
        }
        
        stage('Ejecutar Pruebas') {
            steps {
                sh 'npm test'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'coverage/**', allowEmptyArchive: true
        }
    }
}
